import type { Template } from "../template-engine";

export const infoTemplates: Template[] = [
    {
        id: "info_sac_policy",
        action: "PROVIDE_POLICY",
        intent: "INFO_SAC_POLICY",
        state: ["greeting", "discovery", "proposal", "closing", "support", "support_sac"],
        requiredSlots: [],
        slotConditions: { infoTopic: "exchange" },
        template: "Voce consegue sim 😊 Troca e em ate 30 dias com etiqueta e nota fiscal. Leva tambem um documento com foto. Quer que eu ja te ajude a ver outra opcao pra trocar na loja?",
        maxChars: 190,
        maxQuestions: 1,
    },
    {
        id: "info_refund_policy",
        action: "PROVIDE_POLICY",
        intent: "INFO_SAC_POLICY",
        state: ["greeting", "discovery", "proposal", "closing", "support", "support_sac"],
        requiredSlots: [],
        slotConditions: { infoTopic: "refund" },
        template: "Entendi 👍 O estorno pode levar ate 6 dias uteis (e no cartao pode aparecer em ate 2 faturas, conforme o banco). Se ja passou desse prazo, me passa o numero do pedido que eu verifico.",
        maxChars: 190,
        maxQuestions: 0,
    },
    {
        id: "info_troca_presente",
        action: "PROVIDE_POLICY",
        intent: "INFO_SAC_POLICY",
        state: ["greeting", "discovery", "proposal", "closing", "support", "support_sac"],
        requiredSlots: ["motivoTroca"],
        slotConditions: { motivoTroca: "presente" },
        template: "Troca de presente tambem pode 😊 Em geral e ate 30 dias, com etiqueta e comprovante/nota. Quer que eu te explique certinho o que levar e ja te mostre opcoes pra troca?",
        maxChars: 180,
        maxQuestions: 1,
    },
    {
        id: "info_troca_prazo",
        action: "PROVIDE_POLICY",
        intent: "INFO_SAC_POLICY",
        state: ["greeting", "discovery", "proposal", "closing", "support", "support_sac"],
        requiredSlots: [],
        slotConditions: { infoTopic: "exchange" },
        template: "O prazo para troca e de 30 dias 😊 Basta levar o produto sem uso, com etiqueta e nota fiscal. Quer que eu te ajude a ver opcoes antes de voce ir?",
        maxChars: 180,
        maxQuestions: 1,
    },
    {
        id: "info_garantia_defeito",
        action: "PROVIDE_POLICY",
        intent: "INFO_SAC_POLICY",
        state: ["greeting", "discovery", "proposal", "closing", "support", "support_sac"],
        requiredSlots: ["motivoTroca"],
        slotConditions: { motivoTroca: "defeito" },
        template: "Poxa, entendi 😕 Defeito tem garantia de 90 dias. Traz o produto com nota fiscal que a loja analisa e te orienta certinho. Se quiser, me diz o que aconteceu e eu te direciono melhor.",
        maxChars: 190,
        maxQuestions: 1,
    },
    {
        id: "info_sac_policy_generic",
        action: "PROVIDE_POLICY",
        intent: "INFO_SAC_POLICY",
        state: ["greeting", "discovery", "proposal", "closing", "support", "support_sac"],
        requiredSlots: [],
        template: "Consigo te orientar sim 😊 Me fala se sua duvida e sobre troca, devolucao/reembolso, garantia ou retirada na loja que eu te respondo certinho.",
        maxChars: 170,
        maxQuestions: 1,
    },
    {
        id: "info_pickup_policy_third_party",
        action: "PROVIDE_POLICY",
        intent: ["INFO_PICKUP_POLICY"],
        state: ["greeting", "discovery", "support", "support_sac", "proposal", "closing"],
        requiredSlots: [],
        template: "Sim 😊 Outra pessoa pode retirar com documento com foto, seus dados e o codigo/token de liberacao do pedido. Quer que eu te passe um checklist rapido do que levar?",
        maxChars: 180,
        maxQuestions: 1,
    },
    {
        id: "info_hours_only",
        action: "PROVIDE_POLICY",
        intent: ["INFO_HOURS"],
        state: ["greeting", "discovery", "support", "support_sac", "proposal", "closing"],
        requiredSlots: [],
        template: "Horario da loja 😊 Seg a sab 10h-22h e dom/feriados 12h-20h. Quer que eu ja te ajude a ver um produto antes de voce vir?",
        maxChars: 160,
        maxQuestions: 1,
    },
    {
        id: "info_address_only",
        action: "PROVIDE_POLICY",
        intent: ["INFO_ADDRESS"],
        state: ["greeting", "discovery", "support", "support_sac", "proposal", "closing"],
        requiredSlots: ["addressText"],
        template: "Endereco: {addressText}. Quer que eu te oriente no que levar pra troca/retirada ou veja um produto antes?",
        maxChars: 260,
        maxQuestions: 1,
    },
    {
        id: "info_location_and_hours",
        action: "PROVIDE_POLICY",
        intent: ["INFO"],
        state: ["greeting", "discovery", "support", "support_sac", "proposal", "closing"],
        requiredSlots: ["addressText"],
        template: "Endereco: {addressText}. Horario: seg a sab 10h-22h e dom/feriados 12h-20h. Quer ajuda com troca, retirada ou produto?",
        maxChars: 260,
        maxQuestions: 1,
    },
    {
        id: "info_hours",
        action: "PROVIDE_POLICY",
        intent: ["INFO", "SALES", "SUPPORT", "CLARIFICATION"],
        state: ["greeting", "discovery", "support", "support_sac"],
        requiredSlots: [],
        template: "Horario: seg a sab 10h-22h e dom/feriados 12h-20h.",
        maxChars: 80,
        maxQuestions: 0,
    },
    {
        id: "info_location",
        action: "PROVIDE_POLICY",
        intent: ["INFO", "SALES", "SUPPORT", "CLARIFICATION"],
        state: ["greeting", "discovery", "support", "support_sac"],
        requiredSlots: ["addressText"],
        template: "Endereco da loja: {addressText}",
        maxChars: 220,
        maxQuestions: 0,
    },
    {
        id: "info_confirm_store",
        action: "PROVIDE_POLICY",
        intent: ["INFO", "SALES", "SUPPORT", "CLARIFICATION"],
        state: ["greeting"],
        requiredSlots: [],
        template: "Somos a Centauro de Petrolina.",
        maxChars: 40,
        maxQuestions: 0,
    },
    {
        id: "info_welcome",
        action: "ASK_PRODUCT",
        intent: ["SALES", "CLARIFICATION"],
        state: ["greeting"],
        requiredSlots: [],
        template: "Ola! Seja bem-vindo a Centauro Petrolina! O que voce procura?",
        maxChars: 70,
        maxQuestions: 1,
    },
    {
        id: "info_greeting_clarification",
        action: "LLM_FALLBACK",
        intent: ["CLARIFICATION"],
        state: ["greeting"],
        requiredSlots: [],
        template: "Oi! Sou o Cadu da Centauro Petrolina. Como posso te ajudar?",
        maxChars: 70,
        maxQuestions: 1,
    },
    {
        id: "clarification_tone_repair_ask_product",
        action: "ASK_PRODUCT",
        intent: "CLARIFICATION",
        state: ["discovery", "proposal", "closing"],
        requiredSlots: [],
        template: "Foi mal pelo tom. Quero te ajudar melhor. Qual produto esportivo voce procura?",
        maxChars: 90,
        maxQuestions: 1,
    },
    {
        id: "clarification_tone_repair_ask_usage",
        action: "ASK_USAGE",
        intent: "CLARIFICATION",
        state: ["discovery", "proposal", "closing"],
        requiredSlots: ["product"],
        template: "Foi mal pelo tom. Pra te indicar melhor, voce vai usar pra corrida, academia ou dia a dia?",
        maxChars: 100,
        maxQuestions: 1,
    },
    {
        id: "clarification_tone_repair_ask_size_with_context",
        action: "ASK_SIZE",
        intent: "CLARIFICATION",
        state: ["discovery", "proposal", "closing"],
        requiredSlots: ["usage"],
        template: "Perdao pelo tom. Pra uso em {usage}, qual numero voce calca?",
        maxChars: 85,
        maxQuestions: 1,
    },
    {
        id: "clarification_tone_repair_ask_size",
        action: "ASK_SIZE",
        intent: "CLARIFICATION",
        state: ["discovery", "proposal", "closing"],
        requiredSlots: [],
        template: "Perdao pelo tom. Qual sua numeracao pra eu te ajudar certinho?",
        maxChars: 75,
        maxQuestions: 1,
    },
    {
        id: "info_generic",
        action: "LLM_FALLBACK",
        intent: ["SALES", "SUPPORT", "CLARIFICATION"],
        state: ["greeting", "discovery"],
        requiredSlots: [],
        template: "Como posso te ajudar hoje?",
        maxChars: 30,
        maxQuestions: 1,
    },
];
