import type { Template } from "../template-engine";

export const sacTemplates: Template[] = [
    {
        id: "sac_troca_policy",
        action: "PROVIDE_POLICY",
        intent: "SAC_TROCA",
        state: ["support", "support_sac", "greeting", "discovery", "proposal", "closing"],
        requiredSlots: [],
        template: "Troca: ate 30 dias p/ itens sem uso com etiqueta e nota fiscal. Necessario documento com foto. Vou verificar o seu caso!",
        maxChars: 125,
        maxQuestions: 0,
    },
    {
        id: "sac_troca_tamanho",
        action: "PROVIDE_POLICY",
        intent: "SAC_TROCA",
        state: ["support", "support_sac", "greeting", "discovery", "proposal", "closing"],
        requiredSlots: [],
        template: "Troca tamanho: ate 30 dias com etiqueta, nota fiscal e documento com foto. Vou verificar o seu caso!",
        maxChars: 100,
        maxQuestions: 0,
    },
    {
        id: "sac_troca_request_data",
        action: "REQUEST_ORDER_DATA",
        intent: "SAC_TROCA",
        state: ["support", "support_sac", "greeting", "discovery", "proposal", "closing"],
        requiredSlots: [],
        template: "Me passa o numero do pedido (se online) ou o seu CPF (se loja fisica) que vou verificar.",
        maxChars: 95,
        maxQuestions: 1,
    },
    {
        // Loja física: pedido é OPCIONAL, só precisa CPF e descrição do problema
        id: "sac_troca_loja_fisica",
        action: "REQUEST_ORDER_DATA",
        intent: "SAC_TROCA",
        state: ["support", "support_sac", "greeting", "discovery", "proposal", "closing"],
        requiredSlots: [],
        slotConditions: { canalVenda: "loja_fisica" },
        template: "Entendi. Como foi em loja, me passa seu CPF que vou verificar. O defeito foi com quanto tempo de uso?",
        maxChars: 105,
        maxQuestions: 2,
    },
    {
        // Defeito com garantia de 90 dias
        id: "sac_defeito_garantia",
        action: "PROVIDE_POLICY",
        intent: "SAC_TROCA",
        state: ["support", "support_sac", "greeting", "discovery", "proposal", "closing"],
        requiredSlots: [],
        template: "Defeito tem garantia de 90 dias. Traze o produto na loja com nota fiscal que a gente analisa e troca. Vou registrar o seu caso!",
        maxChars: 130,
        maxQuestions: 0,
    },
    {
        id: "sac_atraso_request_data",
        action: "REQUEST_ORDER_DATA",
        intent: "SAC_ATRASO",
        state: ["support", "support_sac", "greeting", "discovery", "proposal", "closing"],
        requiredSlots: [],
        template: "Me passa o numero do pedido (se online) ou o seu CPF (se loja fisica) que vou verificar.",
        maxChars: 95,
        maxQuestions: 1,
    },
    {
        id: "sac_atraso_policy",
        action: "PROVIDE_POLICY",
        intent: "SAC_ATRASO",
        state: ["support", "support_sac", "greeting", "discovery", "proposal", "closing"],
        requiredSlots: ["orderId"],
        template: "Vou verificar o status do seu pedido agora.",
        maxChars: 50,
        maxQuestions: 0,
    },
    {
        id: "sac_retirada_request_data",
        action: "REQUEST_ORDER_DATA",
        intent: "SAC_RETIRADA",
        state: ["support", "support_sac", "greeting", "discovery", "proposal", "closing"],
        requiredSlots: [],
        template: "Me passa o numero do pedido (se online) ou o seu CPF (se loja fisica) que vou verificar.",
        maxChars: 95,
        maxQuestions: 1,
    },
    {
        id: "sac_retirada_pronto",
        action: "PROVIDE_POLICY",
        intent: "SAC_RETIRADA",
        state: ["support", "support_sac", "greeting", "discovery", "proposal", "closing"],
        requiredSlots: ["orderId"],
        template: "Seu pedido esta pronto! Vou confirmar os detalhes. Venha buscar na Centauro Petrolina Shopping.",
        maxChars: 100,
        maxQuestions: 0,
    },
    {
        id: "sac_reembolso_policy",
        action: "PROVIDE_POLICY",
        intent: "SAC_REEMBOLSO",
        state: ["support", "support_sac", "greeting", "discovery", "proposal", "closing"],
        requiredSlots: [],
        template: "Estorno: apos aprovacao, cai em 72h no Pix, 1-7 dias no Debito ou ate 2 faturas no Credito. Vou acompanhar o seu caso!",
        maxChars: 120,
        maxQuestions: 0,
    },
    {
        id: "sac_reembolso_request_data",
        action: "REQUEST_ORDER_DATA",
        intent: "SAC_REEMBOLSO",
        state: ["support", "support_sac", "greeting", "discovery", "proposal", "closing"],
        requiredSlots: [],
        template: "Me passa o numero do pedido (se online) ou o seu CPF (se loja fisica) que vou verificar.",
        maxChars: 95,
        maxQuestions: 1,
    },
    {
        id: "sac_escalate",
        action: "ESCALATE",
        intent: ["SAC_TROCA", "SAC_ATRASO", "SAC_RETIRADA", "SAC_REEMBOLSO", "HANDOFF"],
        state: ["support", "support_sac", "greeting", "discovery", "proposal", "closing"],
        requiredSlots: [],
        template: "Vou passar pra equipe resolver isso agora. Um instante.",
        maxChars: 60,
        maxQuestions: 0,
    },
    {
        id: "sac_escalate_frustrated",
        action: "ESCALATE",
        intent: ["SAC_TROCA", "SAC_ATRASO", "SAC_RETIRADA", "SAC_REEMBOLSO", "HANDOFF"],
        state: ["support", "support_sac", "greeting", "discovery", "proposal", "closing"],
        requiredSlots: [],
        template: "Compreendo. Vou te transferir para um especialista agora!",
        maxChars: 60,
        maxQuestions: 0,
    },
    {
        id: "sac_need_info",
        action: "REQUEST_ORDER_DATA",
        intent: "SUPPORT",
        state: ["support", "support_sac", "greeting", "discovery", "proposal", "closing"],
        requiredSlots: [],
        template: "Me passa o pedido (se online) ou CPF (se loja), e me conta o que aconteceu. Vou verificar!",
        maxChars: 95,
        maxQuestions: 1,
    },
    {
        id: "sac_clarification_request_data",
        action: "REQUEST_ORDER_DATA",
        intent: "CLARIFICATION",
        state: ["support_sac"],
        requiredSlots: [],
        template: "Me passa o numero do pedido (online) ou seu CPF (loja) que vou verificar.",
        maxChars: 80,
        maxQuestions: 1,
    },
];
