import type { Template } from "../template-engine";

export const sacTemplates: Template[] = [
    {
        id: "sac_troca_policy",
        action: "PROVIDE_POLICY",
        intent: "SAC_TROCA",
        state: ["support", "support_sac"],
        requiredSlots: [],
        template: "Troca: ate 30 dias p/ itens sem uso com etiqueta e nota fiscal. Necessario documento com foto.",
        maxChars: 110,
        maxQuestions: 0,
    },
    {
        id: "sac_troca_tamanho",
        action: "PROVIDE_POLICY",
        intent: "SAC_TROCA",
        state: ["support", "support_sac"],
        requiredSlots: [],
        template: "Troca tamanho: ate 30 dias com etiqueta, nota fiscal e documento com foto.",
        maxChars: 100,
        maxQuestions: 0,
    },
    {
        id: "sac_troca_request_data",
        action: "REQUEST_ORDER_DATA",
        intent: "SAC_TROCA",
        state: ["support", "support_sac"],
        requiredSlots: [],
        template: "Me passa nome completo e numero do pedido ou email pra eu verificar, por favor.",
        maxChars: 95,
        maxQuestions: 1,
    },
    {
        // Loja física: pedido é OPCIONAL, só precisa CPF e descrição do problema
        id: "sac_troca_loja_fisica",
        action: "REQUEST_ORDER_DATA",
        intent: "SAC_TROCA",
        state: ["support", "support_sac"],
        requiredSlots: [],
        slotConditions: { canalVenda: "loja_fisica" },
        template: "Entendi. Como foi em loja, me passa seu CPF pra eu verificar. O defeito foi com quanto tempo de uso?",
        maxChars: 105,
        maxQuestions: 2,
    },
    {
        // Defeito com garantia de 90 dias
        id: "sac_defeito_garantia",
        action: "PROVIDE_POLICY",
        intent: "SAC_TROCA",
        state: ["support", "support_sac"],
        requiredSlots: [],
        template: "Defeito tem garantia de 90 dias. Traze o produto na loja com nota fiscal que a gente analisa e troca.",
        maxChars: 100,
        maxQuestions: 0,
    },
    {
        id: "sac_atraso_request_data",
        action: "REQUEST_ORDER_DATA",
        intent: "SAC_ATRASO",
        state: ["support", "support_sac"],
        requiredSlots: [],
        template: "Me passa nome completo e numero do pedido ou email pra eu verificar, por favor.",
        maxChars: 95,
        maxQuestions: 1,
    },
    {
        id: "sac_atraso_policy",
        action: "PROVIDE_POLICY",
        intent: "SAC_ATRASO",
        state: ["support", "support_sac"],
        requiredSlots: ["orderId"],
        template: "Vou verificar o status do seu pedido agora.",
        maxChars: 50,
        maxQuestions: 0,
    },
    {
        id: "sac_retirada_request_data",
        action: "REQUEST_ORDER_DATA",
        intent: "SAC_RETIRADA",
        state: ["support", "support_sac"],
        requiredSlots: [],
        template: "Me passa nome completo e numero do pedido ou email pra eu verificar, por favor.",
        maxChars: 95,
        maxQuestions: 1,
    },
    {
        id: "sac_retirada_pronto",
        action: "PROVIDE_POLICY",
        intent: "SAC_RETIRADA",
        state: ["support", "support_sac"],
        requiredSlots: ["orderId"],
        template: "Seu pedido esta pronto. Venha buscar na Centauro Petrolina Shopping.",
        maxChars: 75,
        maxQuestions: 0,
    },
    {
        id: "sac_reembolso_policy",
        action: "PROVIDE_POLICY",
        intent: "SAC_REEMBOLSO",
        state: ["support", "support_sac"],
        requiredSlots: [],
        template: "Estorno: apos aprovacao (6 dias uteis), cai em ate 72h no Pix ou ate 2 faturas no cartao.",
        maxChars: 110,
        maxQuestions: 0,
    },
    {
        id: "sac_reembolso_request_data",
        action: "REQUEST_ORDER_DATA",
        intent: "SAC_REEMBOLSO",
        state: ["support", "support_sac"],
        requiredSlots: [],
        template: "Me passa nome completo e numero do pedido ou email pra eu verificar, por favor.",
        maxChars: 95,
        maxQuestions: 1,
    },
    {
        id: "sac_escalate",
        action: "ESCALATE",
        intent: ["SAC_TROCA", "SAC_ATRASO", "SAC_RETIRADA", "SAC_REEMBOLSO", "HANDOFF"],
        state: ["support", "support_sac"],
        requiredSlots: [],
        template: "Vou passar pra equipe resolver isso agora. Um instante.",
        maxChars: 60,
        maxQuestions: 0,
    },
    {
        id: "sac_escalate_frustrated",
        action: "ESCALATE",
        intent: ["SAC_TROCA", "SAC_ATRASO", "SAC_RETIRADA", "SAC_REEMBOLSO", "HANDOFF"],
        state: ["support", "support_sac"],
        requiredSlots: [],
        template: "Compreendo. Vou te transferir para um especialista agora!",
        maxChars: 60,
        maxQuestions: 0,
    },
    {
        id: "sac_need_info",
        action: "REQUEST_ORDER_DATA",
        intent: "SUPPORT",
        state: ["support", "support_sac"],
        requiredSlots: [],
        template: "Me passa nome completo e numero do pedido ou email, e me diz o que aconteceu.",
        maxChars: 95,
        maxQuestions: 1,
    },
    {
        id: "sac_clarification_request_data",
        action: "REQUEST_ORDER_DATA",
        intent: "CLARIFICATION",
        state: ["support_sac"],
        requiredSlots: [],
        template: "Pra eu verificar, me passa nome completo e numero do pedido ou email, por favor.",
        maxChars: 95,
        maxQuestions: 1,
    },
];
