import type { Template } from "../template-engine";

export const salesTemplates: Template[] = [
    {
        id: "sales_greeting_night",
        action: "ASK_PRODUCT",
        intent: "SALES",
        state: "greeting",
        requiredSlots: [],
        template: "Boa noite! Sou o Cadu da Centauro Petrolina. Tá procurando algo pra corrida, treino ou dia a dia?",
        maxChars: 100,
        maxQuestions: 1,
    },
    {
        id: "sales_greeting_day",
        action: "ASK_PRODUCT",
        intent: "SALES",
        state: "greeting",
        requiredSlots: [],
        template: "Bom dia! Sou o Cadu da Centauro Petrolina. Tá procurando algo pra corrida, treino ou dia a dia?",
        maxChars: 100,
        maxQuestions: 1,
    },
    {
        id: "sales_greeting_afternoon",
        action: "ASK_PRODUCT",
        intent: "SALES",
        state: "greeting",
        requiredSlots: [],
        template: "Boa tarde! Sou o Cadu da Centauro Petrolina. Tá procurando algo pra corrida, treino ou dia a dia?",
        maxChars: 100,
        maxQuestions: 1,
    },
    {
        id: "sales_greeting_generic",
        action: "ASK_PRODUCT",
        intent: "SALES",
        state: "greeting",
        requiredSlots: [],
        template: "Ola! Sou o Cadu da Centauro Petrolina. Como posso te ajudar hoje?",
        maxChars: 70,
        maxQuestions: 1,
    },
    {
        id: "sales_ask_product_discovery",
        action: "ASK_PRODUCT",
        intent: "SALES",
        state: "discovery",
        requiredSlots: [],
        template: "Qual produto voce procura?",
        maxChars: 40,
        maxQuestions: 1,
    },
    {
        id: "sales_ask_usage",
        action: "ASK_USAGE",
        intent: "SALES",
        state: ["discovery", "proposal", "closing"],
        requiredSlots: ["product"],
        template: "Pra qual uso voce vai usar? Corrida, academia ou dia a dia?",
        maxChars: 70,
        maxQuestions: 1,
    },
    {
        id: "sales_ask_usage_bola",
        action: "ASK_USAGE",
        intent: "SALES",
        state: ["discovery", "proposal", "closing"],
        requiredSlots: ["categoria"],
        slotConditions: { categoria: "bola" },
        template: "Pra qual esporte? Volei, futebol, basquete ou outro?",
        maxChars: 65,
        maxQuestions: 1,
    },
    {
        id: "sales_ask_usage_with_product",
        action: "ASK_USAGE",
        intent: "SALES",
        state: ["discovery", "proposal", "closing"],
        requiredSlots: ["product"],
        template: "Entendi. Pra qual atividade voce vai usar?",
        maxChars: 55,
        maxQuestions: 1,
    },
    {
        id: "sales_ask_size_apparel",
        action: "ASK_SIZE",
        intent: ["SALES", "RESERVATION", "CLOSING_SALE"],
        state: ["discovery", "proposal", "closing"],
        requiredSlots: ["categoria"],
        slotConditions: { categoria: "vestuario" },
        template: "Boa. Qual tamanho? PP, P, M, G ou GG?",
        maxChars: 50,
        maxQuestions: 1,
    },
    {
        id: "sales_ask_size",
        action: "ASK_SIZE",
        intent: ["SALES", "RESERVATION", "CLOSING_SALE"],
        state: ["discovery", "proposal", "closing"],
        requiredSlots: ["product"],
        template: "Qual sua numeracao?",
        maxChars: 30,
        maxQuestions: 1,
    },
    {
        id: "sales_ask_size_with_context",
        action: "ASK_SIZE",
        intent: ["SALES", "RESERVATION", "CLOSING_SALE"],
        state: ["discovery", "proposal", "closing"],
        requiredSlots: ["product", "usage"],
        template: "Pra uso em {usage}, qual numero voce calca?",
        maxChars: 55,
        maxQuestions: 1,
    },
    {
        id: "sales_ask_size_apparel_with_context",
        action: "ASK_SIZE",
        intent: ["SALES", "RESERVATION", "CLOSING_SALE"],
        state: ["discovery", "proposal", "closing"],
        requiredSlots: ["product", "usage"],
        slotConditions: { categoria: "vestuario" },
        template: "Pra usar em {usage}, qual tamanho voce procura? PP, P, M, G ou GG?",
        maxChars: 80,
        maxQuestions: 1,
    },
    {
        id: "sales_show_product",
        action: "SHOW_PRODUCT",
        intent: "SALES",
        state: ["discovery", "proposal"],
        requiredSlots: ["product", "usage", "size"],
        template: "Achei opcao para {usage} no tamanho {size}. Quer que eu te mostre?",
        maxChars: 75,
        maxQuestions: 1,
    },
    {
        id: "sales_offer_reservation",
        action: "OFFER_RESERVATION",
        intent: ["SALES", "OBJECTION", "RESERVATION", "CLOSING_SALE"],
        state: ["proposal", "closing"],
        requiredSlots: ["product", "size"],
        template: "Temos {product} no tamanho {size}. Quer que eu separe pra voce?",
        maxChars: 75,
        maxQuestions: 1,
    },
    {
        id: "sales_offer_reservation_alt",
        action: "OFFER_RESERVATION",
        intent: ["SALES", "OBJECTION", "RESERVATION", "CLOSING_SALE"],
        state: ["proposal", "closing"],
        requiredSlots: ["product", "size"],
        template: "Perfeito. {product} tam {size} disponivel. Reservo pra voce?",
        maxChars: 75,
        maxQuestions: 1,
    },
    {
        id: "sales_objection_preco",
        action: "LLM_FALLBACK",
        intent: "OBJECTION",
        state: ["proposal", "closing", "objection"],
        requiredSlots: [],
        template: "Entendi. Posso te mostrar uma opcao com melhor custo-beneficio. Qual faixa de preco voce quer?",
        maxChars: 120,
        maxQuestions: 1,
    },
    {
        id: "sales_closing_confirm",
        action: "OFFER_RESERVATION",
        intent: ["SALES", "RESERVATION", "CLOSING_SALE"],
        state: "closing",
        requiredSlots: ["product", "size"],
        template: "Perfeito. Vou reservar {product} tamanho {size} pra voce.",
        maxChars: 70,
        maxQuestions: 0,
    },
    {
        id: "sales_need_more_info",
        action: "ASK_PRODUCT",
        intent: "SALES",
        state: ["discovery", "proposal", "closing"],
        requiredSlots: [],
        template: "Me conta melhor o que voce procura.",
        maxChars: 45,
        maxQuestions: 1,
    },
];
